version: "3.9"
services:
  backend:
    image: diamond-wallet-main-backend:latest
    container_name: diamond-wallet-go
    depends_on:
      - db
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_DRIVER=${DB_DRIVER}
      - PASSWORD=${DB_PASSWORD}
      - LOG_FILE=${LOG_FILE}
      - TOKEN_LIFE_TIME=${TOKEN_LIFE_TIME}
      - TOKEN_ISSUE_NAME=${TOKEN_ISSUE_NAME}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - APP_NAME=${APP_NAME}
      - TOKEN_KEY=${TOKEN_KEY}
    ports:
      - "${API_PORT}:8888"
    networks:
      - product-network
  db:
    image: postgres:alpine3.17
    container_name: diamond-wallet-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - product-network
volumes:
  db-data:
networks:
  product-network:
